server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/

  #  # 默认值是true
  #  eureka.server.enable-self-preservation=true
  #  # default is 30
  #  eureka.instance.leaseRenewalIntervalInSeconds=30
  #  # default is 0.85 we can set the value to 0.49
  #  eureka.server.renewalPercentThreshold=0.49

  server:
    enable-self-preservation: true
    renewal-percent-threshold: 0.49
  instance:
    lease-renewal-interval-in-seconds: 30



